apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: deliverables
  namespace: tap-install
spec:
  fetch:
  - git:
      url: ssh://git@github.com/pakiheart/tap-gitops-config.git
      ref: origin/main
      secretRef: 
        name: sync-git-ssh
  template:
  - ytt: {}
  deploy:
  - kapp:
      rawOptions:
      - --dangerous-override-ownership-of-existing-resources=true
      - --dangerous-allow-empty-list-of-resources=true
      - --diff-changes=true















