#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-gui-cert
  namespace: default
  annotations:
    kapp.k14s.io/change-group: eso/tap-gui-cert
    kapp.k14s.io/change-rule.0: "upsert after upserting eso/secretstore"
spec:
  secretStoreRef:
    name: tap-gui-cert-secrets
    kind: SecretStore
  refreshInterval: "1m"
  data:
    - secretKey: tls.crt
      remoteRef:  #@ data.values.tap_install.secrets.eso.remote_refs.tap_sensitive_values.tap-gui-cert-values_yaml.tls.crt
    - secretKey: tls.key
      remoteRef: #@ data.values.tap_install.secrets.eso.remote_refs.tap_sensitive_values.tap-gui-cert-values_yaml.tls.key
